language: ruby
rvm:
- 2.3.1
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: GOVOKqGnVNPamFFcHNslxXVjVqHvj/0M5rKxEG7WWUBEJsTiydRbBuerG2qX1nMEeuOb/+UskZudUU2dE0x/tv669KSteUSzt87vYdSyMaXdvbogvMmvWGMNALEw6BCmKNp7DQsweFKEKTwJLCzHg6jAYHr8EjDlJDDaIb/iIskBmSklY0PeA4WsS7WW4JQKINlyCCJzvXyRn2cOf2lSjodUMWhVvWbObHVQjmpBs4Q3ZMOqXl3ULEVsWg9+qNTMqZ9MrjDX9xDIfZxZIPMvSdStQXTIj5b6r4mfcOc35hMFQCm1h0p9mU3zVs8/7Eft6AiBDL4T+EYfC/KW0t77FVZPV0RLQwx8eFMTDPYtQI0Z30cvND6M4q2uY5Db/JoRwg+EGVfXKpmotREKuo9mfDZp5EPk+TO6pLfqwB1XUo9bGSre90u9kVQZfe/C6Tkg8h3KAguPg6pGFWrX3wC3Giqfy56Alu7b+aszOT0VMWQ9oV9CuSIIjK6XA+GZUzGYq5q9TwU2ErtJhdjh7+8XnRcheOrcuxngUTXEJEvhy1uBF9SvdiPm9tFvCYA0a/sbS3fjvvff76nQKnzxkAJtXydF7moaiT4k3t1tc1XE8RnK/FtkRMWavzg4UzrsT5KB0qTVzUy6MR53Ed1vtoLU3O6L1x1pcDosI7FhKTzqqRM=
  app: sarahs-library
  on:
    repo: sdossettswift/sarahs_library
