language: ruby
rvm:
- 2.3.1
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: ZcWjWPye+SgdU1nJllTOzexzRBxozWz/yUy2PqceEBCpZesM2Kfb9fO4YGhhwIyGY86NXaNILkhjGCq04vsvHznVMfReMykkuw12COci3cNhmbv5exMuK7iUMlEIcm6eF8nR/04YtCA1gzVQQ/n+3svYEzzicGoHagHir+3XFgOZN302DoXPIcsICO2wGZuLDDv1cEl2a8nmTY3a7yEIaktcXih04+z+3QAKdR9g2FvxkhIMAcfuJZGG13nbb7JUGJQS/GeytQHXLqqYwYIGuf6PTlFsQbT/uxKttK4iD48+RIDM2vhqD2xH0qoM7bkPHK0ymy384MUu1PD+mTHWJbxS4AJy3JpBhi1t8ym2+eTFLQLZU2Atns8uoVdHtBjfBuRkUSxpa50nHBxD8bo/xD3ykDBHN5MQB1zz5cp9P1ogOuiitrPp9ao8iP26pp/jp61nOL/h4VcMyKSr++FQGOfeSAzWN3veDWhQTAbeFbwUK/hq1AMfm0kuO758CgRTzK2pcnvYFgQe+b9lOpoNYH9YkOkEYR9Ry0OTx1z3vX6rALHO1ny0AkDoGR/jUg2lQf2H8OuMxFpGbhRJGwFNCVAN2BPg+P8TaeeoNjkbOmMh0veygNBs1PLnaf7Vnm1IiL3f/yroiBSVPnfAMfuwc/N3J6k+dZ4VdBXoPUZOd/0=
  app: sarahs_library
  on:
    repo: sdossettswift/sarahs_library
