
sarah = User.create! username: "sarah", password: "12345678"
###BOOKS########
Book.create! title:'The Sun Also Rises', author: 'Ernest Hemingway', price: 14.50, photo_url:'https://upload.wikimedia.org/wikipedia/en/9/93/Hemingwaysun1.jpg'
Book.create! title:'A Farewell to Arms', author: 'Ernest Hemingway', price: 16.25, photo_url:'https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.bouf.com%2Fassets%2FProduct-66671-1.org.jpg&f=1'
Book.create! title:'The Old Man and the Sea', author: 'Ernest Hemingway', price: 15, photo_url:'https://upload.wikimedia.org/wikipedia/en/7/73/Oldmansea.jpg'
Book.create! title:'Big Magic',author:'Elizabeth Gilbert', price: '18', photo_url:'https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.vogue.com%2Fwp-content%2Fuploads%2F2015%2F09%2F21%2F01-big-magic-book-review.jpg&f=1'
Book.create! title:'I and Thou',author:'Martin Buber', price: '8', photo_url:'https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fimg2.imagesbn.com%2Fp%2F9781578989973_p0_v1_s260x420.JPG&f=1'
Book.create! title:'The Southerners Handbook: A Guide to the Good Life', author:'Editors of Garden & Gun', price: 25, photo_url:'https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fimg2.imagesbn.com%2Fp%2F9780062242389_p0_v5_s260x420.JPG&f=1'
Book.create! title:'The Southerners Cookbook',author:'Editors of Garden & Gun', price: 27, photo_url:'https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.thesouthernc.com%2Fwp-content%2Fuploads%2F2015%2F10%2FScreen-Shot-2015-10-25-at-10.59.21-AM-300x327.png&f=1'
Book.create! title: 'The Sound and the Fury', author: 'William Faulkner', price:12 , photo_url:'https://images-na.ssl-images-amazon.com/images/I/81-4fXFpZ8L.jpg'
Book.create! title: 'As I Lay Dying', author: 'William Faulkner', price:13 , photo_url:'https://images-na.ssl-images-amazon.com/images/I/91B2XZKrFcL.jpg'
Book.create! title: 'Light in August', author: 'William Faulkner', price:14 , photo_url:'https://images-na.ssl-images-amazon.com/images/I/51CvkLzqUbL.jpg'
Book.create! title: 'Infinite Jest', author: 'David Foster Wallace', price:16.50 , photo_url:'https://images-na.ssl-images-amazon.com/images/I/412xPN7BBkL.jpg'
Book.create! title: 'Consider the Lobster', author: 'David Foster Wallace', price: 22.50 , photo_url:'https://images-na.ssl-images-amazon.com/images/I/41LuDLgf0lL._SX331_BO1,204,203,200_.jpg'
Book.create! title: 'Not that Kind of Girl', author: 'Lena Dunham', price:17.50 , photo_url:'https://images-na.ssl-images-amazon.com/images/I/5180DT8QFkL.jpg'
Book.create! title: 'The Girl with the Lower Back Tattoo', author: 'Amy Schumer', price:27.50, photo_url:'https://images-na.ssl-images-amazon.com/images/I/81vhpVDxTRL.jpg'
Book.create! title: 'Americanah', author: 'Chimamanda Ngozi Adichie', price: 13, photo_url:'https://images-na.ssl-images-amazon.com/images/I/51L3ktA41ZL.jpg'
Book.create! title: 'We Should All Be Feminists', author: 'Chimamanda Ngozi Adichie', price: 18, photo_url:'https://images-na.ssl-images-amazon.com/images/I/51Pueh2cUUL.jpg'

Author.create! first_name:'Ernest', last_name:'Hemingway',photo_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/ErnestHemingway.jpg/220px-ErnestHemingway.jpg', bio:'Ernest Miller Hemingway (July 21, 1899 – July 2, 1961) was an American novelist, short story writer, and journalist. His economical and understated style had a strong influence on 20th-century fiction, while his life of adventure and his public image influenced later generations. Hemingway produced most of his work between the mid-1920s and the mid-1950s, and won the Nobel Prize in Literature in 1954. He published seven novels, six short story collections, and two non-fiction works. Additional works, including three novels, four short story collections, and three non-fiction works, were published posthumously. Many of his works are considered classics of American literature.'
Author.create! first_name:'Elizabeth', last_name:'Gilbert',photo_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Elizabeth_Gilbert_at_TED.jpg/220px-Elizabeth_Gilbert_at_TED.jpg', bio:'Elizabeth M. Gilbert (born July 18, 1969) is an American author, essayist, short story writer, biographer, novelist, and memoirist. She is best known for her 2006 memoir, Eat, Pray, Love, which as of December 2010 has spent 199 weeks on the New York Times Best Seller list, and was also made into a film by the same name in 2010.'
Author.create! first_name:'Martin', last_name:'Buber',photo_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Martin_Buber_portrait.jpg/220px-Martin_Buber_portrait.jpg', bio:'Martin Buber (Hebrew: מרטין בובר‎‎, German: Martin Buber, Yiddish: מארטין בובער‎; February 8, 1878 – June 13, 1965) was an Austrian-born Israeli Jewish philosopher best known for his philosophy of dialogue, a form of existentialism centered on the distinction between the I–Thou relationship and the I–It relationship. Born in Vienna, Buber came from a family of observant Jews, but broke with Jewish custom to pursue secular studies in philosophy. In 1902, he became the editor of the weekly Die Welt, the central organ of the Zionist movement, although he later withdrew from organizational work in Zionism. In 1923, Buber wrote his famous essay on existence, Ich und Du (later translated into English as I and Thou), and in 1925, he began translating the Hebrew Bible into the German language.

In 1930, Buber became an honorary professor at the University of Frankfurt am Main, but resigned from his professorship in protest immediately after Adolf Hitler came to power in 1933. He then founded the Central Office for Jewish Adult Education, which became an increasingly important body as the German government forbade Jews to attend public education. In 1938, Buber left Germany and settled in Jerusalem, Mandate Palestine, receiving a professorship at Hebrew University and lecturing in anthropology and introductory sociology.'
Author.create! first_name:'Mircea', last_name:'Eliade',photo_url:'https://upload.wikimedia.org/wikipedia/en/8/8c/Mircea.eliade.jpg', bio:'Mircea Eliade (Romanian: [ˈmirt͡ʃe̯a eliˈade]; March 9 [O.S. February 24] 1907 – April 22, 1986) was a Romanian historian of religion, fiction writer, philosopher, and professor at the University of Chicago. He was a leading interpreter of religious experience, who established paradigms in religious studies that persist to this day. His theory that hierophanies form the basis of religion, splitting the human experience of reality into sacred and profane space and time, has proved influential.[1] One of his most influential contributions to religious studies was his theory of Eternal Return, which holds that myths and rituals do not simply commemorate hierophanies, but, at least to the minds of the religious, actually participate in them.'
Author.create! first_name:'William', last_name:'Faulkner',photo_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Carl_Van_Vechten_-_William_Faulkner.jpg/220px-Carl_Van_Vechten_-_William_Faulkner.jpg', bio:'William Cuthbert Faulkner (/ˈfɔːlknər/, September 25, 1897 – July 6, 1962) was an American writer and Nobel Prize laureate from Oxford, Mississippi. Faulkner wrote novels, short stories, a play, poetry, essays, and screenplays. He is primarily known for his novels and short stories set in the fictional Yoknapatawpha County, based on Lafayette County, Mississippi, where he spent most of his life.'
Author.create! first_name:'David Foster', last_name:'Wallace',photo_url:'https://upload.wikimedia.org/wikipedia/commons/4/43/David_Foster_Wallace_headshot_2006.jpg', bio:'David Foster Wallace (February 21, 1962 – September 12, 2008) was an American novelist, short story writer, and essayist, as well as a professor of English and creative writing. His 1996 novel, Infinite Jest, was cited by Time magazine as one of the 100 best English-language novels from 1923 to 2005. His last, unfinished novel, The Pale King, was published in 2011 and was a finalist for the 2012 Pulitzer Prize for Fiction. A biography of Wallace was published in September 2012, and an extensive critical literature on his work has developed in the past decade.'
Author.create! first_name:'Lena', last_name:'Dunham',photo_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Lena_Dunham_TFF_2012_Shankbone_3.JPG/220px-Lena_Dunham_TFF_2012_Shankbone_3.JPG', bio:'Lena Dunham (born May 13, 1986) is an American actress, writer, producer, and director. She is best known as the creator, writer and star of the HBO series Girls (2012–present), for which she has received numerous Emmy award nominations and two Golden Globe awards.Her work on Girls also led her to become the first woman to win the Directors Guild of America Award for Outstanding Directing – Comedy Series in 2013. That year Dunham was included in the Time 100 list of the most influential people in the world. In 2014, Dunham released her first book, Not That Kind of Girl: A Young Woman Tells You What Shes Learned.'
Author.create! first_name:'Amy', last_name:'Schumer', photo_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Amy_Schumer_by_Mario_Santor.jpg/220px-Amy_Schumer_by_Mario_Santor.jpg', bio:'Amy Beth Schumer (born June 1, 1981) is an American stand-up comedian, writer, actress, and producer. She is the creator, co-producer, co-writer and star of the sketch comedy series Inside Amy Schumer, which debuted on Comedy Central in 2013 and has received a Peabody Award. Schumer has been nominated for five Primetime Emmy Awards for her work on the series, winning for Outstanding Variety Sketch Series in 2015. That year, she also wrote and starred in the comedy film Trainwreck, receiving nominations for the Writers Guild of America Award for Best Original Screenplay and the Golden Globe Award for Best Actress – Motion Picture Comedy or Musical.'
Author.create! first_name:'Chimamanda',last_name:'Ngozi Adichie', photo_url:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Adichie_chimamanda_download_2.JPG/220px-Adichie_chimamanda_download_2.JPG', bio:'Chimamanda Ngozi Adichie (/ˌtʃɪmɑːmɑːndə əŋɡoʊzi ʌdiːtʃeɪ/;[note 1] born 15 September 1977) is a Nigerian novelist, nonfiction writer and short story writer. A MacArthur Genius Grant recipient, Adichie has been called the most prominent of a procession of critically acclaimed young anglophone authors [that] is succeeding in attracting a new generation of readers to African literature'
Author.create! first_name:'The Editors of', last_name: 'Garden & Gun', photo_url:'https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Garden_%26_Gun_logo.png/300px-Garden_%26_Gun_logo.png', bio:'Garden & Gun is based in Charleston, South Carolina and covers an adventure-bound, art-loving, skeet-shooting lifestyle, as well as gardens, Southern tradition and land conservation. The name Garden & Gun is an inside reference to a popular 70s Charleston disco called the Garden and Gun Club. According to Rebecca Darwin, President and CEO of Garden & Gun, the title is a metaphor for the South—its land, the people, their lifestyle, and their heritage.'
